---
apiVersion: v1
kind: Namespace
metadata:
  name: k3os-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    apps.kubernetes.io/component: controller
    apps.kubernetes.io/name: k3os-operator
  name: k3os-operator
  namespace: k3os-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    apps.kubernetes.io/component: controller
    apps.kubernetes.io/name: k3os-operator
  name:  k3os-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: k3os-operator
  namespace: k3os-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3os-operator
  namespace: k3os-system
spec:
  selector:
    matchLabels:
      name: k3os-operator
  template:
    metadata:
      labels:
        name: k3os-operator
        upgrade.k3os.io/operator: k3os-operator
    spec:
      serviceAccountName: k3os-operator
      tolerations:
        - key: "node.kubernetes.io/unschedulable"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: k3os-operator-agent
          image: rancher/pause:3.1
          command: ["k3os", "operator", "agent"]
          env:
            - name: K3OS_DEBUG
              value: 'true'
            - name: K3OS_OPERATOR_NAME
              value: k3os-operator
            - name: K3OS_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K3OS_OPERATOR_THREADS
              value: "2"
            - name: K3OS_OPERATOR_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          volumeMounts:
            - name: etc-ssl
              mountPath: /etc/ssl
            - name: k3os-system
              mountPath: /k3os/system
            - name: run-k3os
              mountPath: /run/k3os
            - name: tmp
              mountPath: /tmp
            - name: usr
              mountPath: /usr
            - name: var-lib-rancher
              mountPath: /var/lib/rancher
      volumes:
        - name: etc-ssl
          hostPath:
            path: /etc/ssl
            type: Directory
        - name: k3os-system
          hostPath:
            path: /k3os/system
            type: Directory
        - name: run-k3os
          hostPath:
            path: /run/k3os
            type: Directory
        - name: tmp
          hostPath:
            path: /tmp
            type: Directory
        - name: usr
          hostPath:
            path: /usr
            type: Directory
        - name: var-lib-rancher
          hostPath:
            path: /var/lib/rancher
            type: Directory
#---
#apiVersion: "k3os.io/v1"
#kind: Channel
#metadata:
#  name: edge
#  namespace: k3os-system
#spec:
#  url: https://github.com/rancher/k3os/releases/latest
