#!/bin/bash
[ "$ARCH" == "arm" ] && exit 0

set -e

source $(dirname $0)/version

cd $(dirname $0)/..

bash -x ./scripts/build
bash -x ./scripts/package

echo Running regression tests
set -x
ID=$(docker run --net=host --privileged --rm -itd -w /go/src/github.com/$REPO/k3os $REPO/k3os-qemu:$TAG go test -v ./pkg/test/... -integration)
docker attach $ID || docker kill $ID
